### ISSUE TITLE
Flat Arrows

### ISSUE THREAD

**Issue by OlivierJM** [DamianoSilverhand/DaSaSi-Notetaker#1]
The other way you could bind do events binding without initializing in the constructor is to to use flat arrows, this is better because you retain the component context and you also get rid of unnecessary lines of code.
Consider cleaning up your code by properly indenting it. 
I can make a pull request to add the suggested, I definitely wouldn't change anything on the interface but the code itself. @DamianoSilverhand @SamuelEli @sithembinkhosi-atanase 

> consider using es6 more often (more practice for you )
an example for the above mentioned 
``` 
changeText(e) { 
   this.setState({text: e.target.value});  
 } 
```
You call the above like this `this.changeText` when it is bound in the constructor and like `this.changeText.bind(this)` to bind it every time the component re-renders.
 
With flat arrows it should become this without binding it in the constructor you just call it like this `this.changeText`. 
> There isn't much advantage from the other one but it makes things cleaner
``` 
changeText = ({target: {value}}) => {
    this.setState({text:value})
}
```

**Comment by DamianoSilverhand** [comment]
You can add the suggested, thanks for highlighting. es6 is definitely better
